spring:
  thymeleaf:
    prefix: classpath:/templates
    cache: false
  mvc:
    favicon:
      enabled: true
    locale: pt_BR
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  
  multipart:
    maxFileSize: 1024KB
    maxRequestSize: 5MB
  mail:
    host: smtp.gmail.com
    username: siapessoalfb@gmail.com
    password:  Fbradesco
    port: 587
    properties.mail.smtp.starttls.enable: true
      
  
            
            
